name: Discord Integration
on: [push]

jobs:
  Send-Discord-Message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Discord Integration
        uses: Sniddl/discord-commits@v1.8
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true
